# Generated by Django 5.0.9 on 2025-11-30 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0003_order_public_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_name', models.CharField(default='Mock', max_length=50)),
                ('tracking_id', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('searching', 'Searching for Driver'), ('confirmed', 'Driver Confirmed'), ('picked_up', 'Picked Up'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='searching', max_length=20)),
                ('estimated_delivery_time', models.DateTimeField(blank=True, null=True)),
                ('driver_name', models.CharField(blank=True, max_length=100, null=True)),
                ('driver_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery', to='orders.order')),
            ],
            options={
                'verbose_name_plural': 'Deliveries',
                'db_table': 'deliveries',
            },
        ),
    ]
