# Generated by Django 5.0.9 on 2025-11-25 19:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='referral',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='referral',
            name='reason',
        ),
        migrations.RemoveField(
            model_name='referral',
            name='token',
        ),
        migrations.RemoveField(
            model_name='referral',
            name='user_limit',
        ),
        migrations.AddField(
            model_name='referral',
            name='code',
            field=models.CharField(default='TEMP00000000', editable=False, max_length=12, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='referral',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='referral',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='referral',
            name='max_uses',
            field=models.IntegerField(default=0, help_text='0 means unlimited'),
        ),
        migrations.AlterField(
            model_name='referral',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='referral',
            name='referral_type',
            field=models.CharField(choices=[('signup', 'Signup Referral'), ('order', 'Order Share')], default='signup', max_length=10),
        ),
        migrations.CreateModel(
            name='ReferralUse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('referral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uses', to='referrals.referral')),
                ('referred_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='used_referrals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'referral_uses',
                'ordering': ['-created_at'],
                'unique_together': {('referral', 'referred_user')},
            },
        ),
    ]
