# Generated by Django 5.0.9 on 2025-11-27 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0002_alter_referral_options_remove_referral_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='referraluse',
            name='referee_bonus_granted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='referraluse',
            name='referrer_bonus_granted',
            field=models.BooleanField(default=False),
        ),
    ]
