# Generated by Django 5.0.9 on 2025-11-30 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0003_referraluse_referee_bonus_granted_and_more'),
        ('wallet', '0003_remove_coinwallet_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='referee_reward_amount',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='referral',
            name='referrer_reward_amount',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='referral',
            name='reward_expiry_days',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='referraluse',
            name='referee_credit',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referral_use_as_referee', to='wallet.walletcredit'),
        ),
        migrations.AddField(
            model_name='referraluse',
            name='referrer_credit',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referral_use_as_referrer', to='wallet.walletcredit'),
        ),
    ]
