# Generated by Django 5.0.9 on 2025-11-27 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coinwallet',
            name='inactive_balance',
            field=models.IntegerField(default=0),
        ),
    ]
