# Generated by Django 5.0.9 on 2025-11-30 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_coinwallet_inactive_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coinwallet',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='coinwallet',
            name='inactive_balance',
        ),
        migrations.CreateModel(
            name='WalletCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('source', models.CharField(choices=[('REFERRAL_SIGNUP', 'Referral Signup Bonus'), ('REFERRAL_REWARD', 'Referrer Reward'), ('ORDER_REWARD', 'Order Reward'), ('MANUAL', 'Manual Adjustment')], max_length=20)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField()),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credits', to='wallet.coinwallet')),
            ],
            options={
                'db_table': 'wallet_credits',
                'ordering': ['expires_at'],
            },
        ),
    ]
