# Generated by Django 5.0.9 on 2025-11-25 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_paymentqrcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='public_id',
            field=models.CharField(default='TEMP00000000', editable=False, max_length=16, unique=True),
            preserve_default=False,
        ),
    ]
